[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
bank-api = { path = "../bank_api" }
tonic.workspace = true
prost.workspace = true
tokio.workspace = true
bytes.workspace = true
byteorder.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { version = "1.51.0", features = ["macros", "rt-multi-thread", "test-util"] }
tonic = { version = "0.14.5", features = ["transport"] }
tokio-retry = "0.3.0"
